name       : fish
version    : 2.7.1
release    : 10
homepage   : http://fishshell.com/
source     :
    - https://github.com/fish-shell/fish-shell/releases/download/2.7.1/fish-2.7.1.tar.gz : e42bb19c7586356905a58578190be792df960fa81de35effb1ca5a5a981f0c5a
license    :
    - GPL-2.0
    - LGPL-2.1
    - BSD-3-Clause
    - MIT
    - ISC
summary    : Fish shell
description: |
    Fish is a smart and user-friendly command line shell for OS X, Linux, and the rest of the family.
component  : shells
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
