name       : fish
version    : '3.0'
release    : 12
homepage   : https://fishshell.com
source     :
    - git|https://github.com/fish-shell/fish-shell.git : 3.0.0
license    :
    # Files have different licenses
    # Licenses like MIT, BSD etc. are related to deps, not fish itself
        - GPL-2.0-only
        - GPL-2.0-or-later
        - GPL-3.0-or-later
component  : system.utils
summary    : A full-blown user-friendly command line shell
description: |
    Fish is a smart and user-friendly command line shell for macOS, Linux, and the rest of the family. Fish includes features like syntax highlighting, autosuggest-as-you-type, and fancy tab completions that just work, with no configuration required.
builddeps  :
    - pkgconfig(libpcre2-posix)
    - doxygen
    - expect
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/usr/etc $installdir/
# check      : |
#    # This test fails because we have no TTYs in solbuild
#    rm tests/test1*
#    %ninja_check
