name       : fish
version    : 2.5.0
release    : 7
homepage   : http://fishshell.com/
source     :
    - https://github.com/fish-shell/fish-shell/releases/download/2.5.0/fish-2.5.0.tar.gz : f8c0edadca2de379ccf305aeace660a9255fa2180c72e85e97705a24c256b2a5
license    :
    - GPL-2.0
    - LGPL-2.1
    - BSD-3-Clause
    - MIT
    - ISC
summary    : Fish shell
description: |
    Fish is a smart and user-friendly command line shell for OS X, Linux, and the rest of the family.
component  : shells
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
