name       : fish
version    : 3.4.0
release    : 22
homepage   : https://fishshell.com
source     :
    - https://github.com/fish-shell/fish-shell/releases/download/3.4.0/fish-3.4.0.tar.xz : b5b48ab8486b19ef716a32f7f46b88b9ea5356155f0e967ee99f4093645413c5
license    :
    # Files have different licenses
    # Licenses like MIT, BSD etc. are related to deps, not fish itself
        - GPL-2.0-only
        - GPL-2.0-or-later
        - GPL-3.0-or-later
component  : system.utils
summary    : A full-blown user-friendly command line shell
description: |
    Fish is a smart and user-friendly command line shell for macOS, Linux, and the rest of the family. Fish includes features like syntax highlighting, autosuggest-as-you-type, and fancy tab completions that just work, with no configuration required.
builddeps  :
    - pkgconfig(libpcre2-posix)
    - expect
    - python-sphinx
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/usr/etc $installdir/
    rm -rf $installdir/usr/share/doc/fish/{_sources,.buildinfo}
# check      : |
#    # This test fails because we have no TTYs in solbuild
#    rm tests/test1*
#    %ninja_check
